var wordList="zgsnvdmlfuplrubt\nvlhagaovgqjmgvwq\nffumlmqwfcsyqpss\nzztdcqzqddaazdjp\neavfzjajkjesnlsb\nurrvucyrzzzooxhx\nxdwduffwgcptfwad\norbryxwrmvkrsxsr\njzfeybjlgqikjcow\nmayoqiswqqryvqdi\niiyrkoujhgpgkcvx\negcgupjkqwfiwsjl\nzbgtglaqqolttgng\neytquncjituzzhsx\ndtfkgggvqadhqbwb\nzettygjpcoedwyio\nrwgwbwzebsnjmtln\nesbplxhvzzgawctn\nvnvshqgmbotvoine\nwflxwmvbhflkqxvo\ntwdjikcgtpvlctte\nminfkyocskvgubvm\nsfxhhdhaopajbzof\nsofkjdtalvhgwpql\nuqfpeauqzumccnrc\ntdflsbtiiepijanf\ndhfespzrhecigzqb\nxobfthcuuzhvhzpn\nolgjglxaotocvrhw\njhkzpfcskutwlwge\nzurkakkkpchzxjhq\nhekxiofhalvmmkdl\nazvxuwwfmjdpjskj\narsvmfznblsqngvb\nldhkzhejofreaucc\nadrphwlkehqkrdmo\nwmveqrezfkaivvaw\niyphmphgntinfezg\nblomkvgslfnvspem\ncgpaqjvzhbumckwo\nydhqjcuotkeyurpx\nsbtzboxypnmdaefr\nvxrkhvglynljgqrg\nttgrkjjrxnxherxd\nhinyfrjdiwytetkw\nsufltffwqbugmozk\ntohmqlzxxqzinwxr\njbqkhxfokaljgrlg\nfvjeprbxyjemyvuq\ngmlondgqmlselwah\nubpwixgxdloqnvjp\nlxjfhihcsajxtomj\nqouairhvrgpjorgh\nnloszcwcxgullvxb\nmyhsndsttanohnjn\nzjvivcgtjwenyilz\nqaqlyoyouotsmamm\ntadsdceadifqthag\nmafgrbmdhpnlbnks\naohjxahenxaermrq\novvqestjhbuhrwlr\nlnakerdnvequfnqb\nagwpwsgjrtcjjikz\nlhlysrshsmzryzes\nxopwzoaqtlukwwdu\nxsmfrfteyddrqufn\nohnxbykuvvlbbxpf\nbbdlivmchvzfuhoc\nvtacidimfcfyobhf\ntinyzzddgcnmiabd\ntcjzxftqcqrivqhn\nvgnduqyfpokbmzim\nrevkvaxnsxospyow\nydpgwxxoxlywxcgi\nwzuxupbzlpzmikel\nnscghlafavnsycjh\nxorwbquzmgmcapon\nasmtiycegeobfxrn\neqjzvgkxgtlyuxok\nmmjrskloposgjoqu\ngceqosugbkvytfto\nkhivvoxkvhrgwzjl\nqtmejuxbafroifjt\nttmukbmpoagthtfl\nbxqkvuzdbehtduwv\ngvblrpzjylanoggj\ncltewhyjxdbmbtqj\nfbkgedqvomdipklj\nuxvuplhenqawfcjt\nfkdjmayiawdkycva\ngnloqfgbnibzyidh\nkyzorvtopjiyyyqg\ndrckpekhpgrioblt\ntvhrkmbnpmkkrtki\nkhaldwntissbijiz\naoojqakosnaxosom\nxfptccznbgnpfyqw\nmoqdwobwhjxhtrow\nchfwivedutskovri\ngprkyalfnpljcrmi\npwyshpwjndasykst\nxuejivogihttzimd\nbugepxgpgahtsttl\nzufmkmuujavcskpq\nurybkdyvsrosrfro\nisjxqmlxwtqmulbg\npxctldxgqjqhulgz\nhclsekryiwhqqhir\nhbuihpalwuidjpcq\nejyqcxmfczqfhbxa\nxljdvbucuxnnaysv\nirqceqtqwemostbb\nanfziqtpqzqdttnz\ncgfklbljeneeqfub\nzudyqkuqqtdcpmuo\niuvhylvznmhbkbgg\nmpgppmgfdzihulnd\nargwmgcvqqkxkrdi\npdhrfvdldkfihlou\ncbvqnjrvrsnqzfob\nlkvovtsqanohzcmm\nvxoxjdyoylqcnyzt\nkurdpaqiaagiwjle\ngwklwnazaxfkuekn\nrbaamufphjsjhbdl\ntzbrvaqvizhsisbd\npbcqlbfjvlideiub\nhiwoetbfywaeddtx\nfjirczxtuupfywyf\nomeoegeyyospreem\nozbbpupqpsskvrjh\npzvcxkvjdiyeyhxa\nodclumkenabcsfzr\nnpdyqezqdjqaszvm\nyodkwzmrhtexfrqa\nrjcmmggjtactfrxz\nmioxfingsfoimual\naqskaxjjborspfaa\nwientdsttkevjtkf\ntdaswkzckmxnfnct\nvoucjhzvkkhuwoqk\nboaaruhalgaamqmh\niufzxutxymorltvb\npfbyvbayvnrpijpo\nobztirulgyfthgcg\nntrenvhwxypgtjwy\nephlkipjfnjfjrns\npkjhurzbmobhszpx\ngqbnjvienzqfbzvj\nwjelolsrbginwnno\nvotanpqpccxqricj\nbxyuyiglnmbtvehi\nqyophcjfknbcbjrb\nanoqkkbcdropskhj\ntcnyqaczcfffkrtl\nrsvqimuqbuddozrf\nmeppxdrenexxksdt\ntyfhfiynzwadcord\nwayrnykevdmywycf\nmhowloqnppswyzbu\ntserychksuwrgkxz\nxycjvvsuaxsbrqal\nfkrdsgaoqdcqwlpn\nvrabcmlhuktigecp\nxgxtdsvpaymzhurx\nciabcqymnchhsxkc\neqxadalcxzocsgtr\ntsligrgsjtrnzrex\nqeqgmwipbspkbbfq\nvzkzsjujltnqwliw\nldrohvodgbxokjxz\njkoricsxhipcibrq\nqzquxawqmupeujrr\nmizpuwqyzkdbahvk\nsuupfxbtoojqvdca\nywfmuogvicpywpwm\nuevmznxmsxozhobl\nvjbyhsemwfwdxfxk\niyouatgejvecmtin\ntcchwpuouypllcxe\nlgnacnphdiobdsef\nuoxjfzmdrmpojgbf\nlqbxsxbqqhpjhfxj\nknpwpcnnimyjlsyz\nfezotpoicsrshfnh\ndkiwkgpmhudghyhk\nyzptxekgldksridv\npckmzqzyiyzdbcts\noqshafncvftvwvsi\nyynihvdywxupqmbt\niwmbeunfiuhjaaic\npkpkrqjvgocvaxjs\nieqspassuvquvlyz\nxshhahjaxjoqsjtl\nfxrrnaxlqezdcdvd\npksrohfwlaqzpkdd\nravytrdnbxvnnoyy\natkwaifeobgztbgo\ninkcabgfdobyeeom\nywpfwectajohqizp\namcgorhxjcybbisv\nmbbwmnznhafsofvr\nwofcubucymnhuhrv\nmrsamnwvftzqcgta\ntlfyqoxmsiyzyvgv\nydceguvgotylwtea\nbtyvcjqhsygunvle\nusquiquspcdppqeq\nkifnymikhhehgote\nybvkayvtdpgxfpyn\noulxagvbavzmewnx\ntvvpekhnbhjskzpj\nazzxtstaevxurboa\nnfmwtfgrggmqyhdf\nynyzypdmysfwyxgr\niaobtgubrcyqrgmk\nuyxcauvpyzabbzgv\nfbasfnwiguasoedc\nmgmjoalkbvtljilq\nszgkxiqkufdvtksb\nxgfzborpavdmhiuj\nhmuiwnsonvfgcrva\nzolcffdtobfntifb\nmvzgcsortkugvqjr\npbbpgraaldqvzwhs\nzvsxegchksgnhpuv\nkdpdboaxsuxfswhx\njdfggigejfupabth\ntpeddioybqemyvqz\nmxsntwuesonybjby\ntzltdsiojfvocige\nubtdrneozoejiqrv\nfusyucnhncoxqzql\nnlifgomoftdvkpby\npyikzbxoapffbqjw\nhzballplvzcsgjug\nymjyigsfehmdsvgz\nvpqgyxknniunksko\nffkmaqsjxgzclsnq\njcuxthbedplxhslk\nymlevgofmharicfs\nnyhbejkndhqcoisy\nrjntxasfjhnlizgm\noqlnuxtzhyiwzeto\ntntthdowhewszitu\nrmxyoceuwhsvfcua\nqpgsjzwenzbxyfgw\nsumguxpdkocyagpu\nymfrbxwrawejkduu\nhetgrtmojolbmsuf\nqzqizpiyfasgttex\nqnmoemcpuckzsshx\nddyqiihagcmnxccu\noirwxyfxxyktgheo\nphpaoozbdogbushy\nuctjdavsimsrnvjn\naurbbphvjtzipnuh\nhpbtrubopljmltep\npyyvkthqfsxqhrxg\njdxaiqzkepxbfejk\nukgnwbnysrzvqzlw\nlfkatkvcssnlpthd\nucsyecgshklhqmsc\nrwdcbdchuahkvmga\nrxkgqakawgpwokum\nhbuyxeylddfgorgu\ntbllspqozaqzglkz\nrqfwizjlbwngdvvi\nxuxduyzscovachew\nkouiuxckkvmetvdy\nycyejrpwxyrweppd\ntrctlytzwiisjamx\nvtvpjceydunjdbez\ngmtlejdsrbfofgqy\njgfbgtkzavcjlffj\ntyudxlpgraxzchdk\ngyecxacqitgozzgd\nrxaocylfabmmjcvt\ntornfzkzhjyofzqa\nkocjcrqcsvagmfqv\nzfrswnskuupivzxb\ncunkuvhbepztpdug\npmpfnmklqhcmrtmf\ntfebzovjwxzumxap\nxpsxgaswavnzkzye\nlmwijdothmxclqbr\nupqxhmctbltxkarl\naxspehytmyicthmq\nxdwrhwtuooikehbk\ntpggalqsytvmwerj\njodysbwnymloeqjf\nrxbazvwuvudqlydn\nibizqysweiezhlqa\nuexgmotsqjfauhzp\nldymyvumyhyamopg\nvbxvlvthgzgnkxnf\npyvbrwlnatxigbrp\nazxynqididtrwokb\nlwafybyhpfvoawto\nogqoivurfcgspytw\ncinrzzradwymqcgu\nsgruxdvrewgpmypu\nsnfnsbywuczrshtd\nxfzbyqtyxuxdutpw\nfmpvjwbulmncykbo\nljnwoslktrrnffwo\nceaouqquvvienszn\nyjomrunrxjyljyge\nxpmjsapbnsdnbkdi\nuetoytptktkmewre\neixsvzegkadkfbua\nafaefrwhcosurprw\nbwzmmvkuaxiymzwc\ngejyqhhzqgsrybni\ngjriqsfrhyguoiiw\ngtfyomppzsruhuac\nogemfvmsdqqkfymr\njgzbipsygirsnydh\nzghvlhpjnvqmocgr\nngvssuwrbtoxtrka\nietahyupkbuisekn\ngqxqwjizescbufvl\neiprekzrygkncxzl\nigxfnxtwpyaamkxf\nsoqjdkxcupevbren\nfspypobyzdwstxak\nqstcgawvqwtyyidf\ngsccjacboqvezxvd\nbfsblokjvrqzphmc\nsrezeptvjmncqkec\nopmopgyabjjjoygt\nmsvbufqexfrtecbf\nuiaqweyjiulplelu\npbkwhjsibtwjvswi\nxwwzstmozqarurrq\nnytptwddwivtbgyq\nejxvsufbzwhzpabr\njouozvzuwlfqzdgh\ngfgugjihbklbenrk\nlwmnnhiuxqsfvthv\nbzvwbknfmaeahzhi\ncgyqswikclozyvnu\nudmkpvrljsjiagzi\nzzuhqokgmisguyna\nekwcdnjzuctsdoua\neueqkdrnzqcaecyd\nlnibwxmokbxhlris\nfdrbftgjljpzwhea\niabvuhhjsxmqfwld\nqgogzkynrgejakta\nmfcqftytemgnpupp\nklvhlhuqhosvjuqk\ngdokmxcgoqvzvaup\njuududyojcazzgvr\nfyszciheodgmnotg\nyfpngnofceqfvtfs\ncahndkfehjumwavc\ndxsvscqukljxcqyi\ncqukcjtucxwrusji\nvevmmqlehvgebmid\nahswsogfrumzdofy\nftasbklvdquaxhxb\ntsdeumygukferuif\nybfgbwxaaitpwryg\ndjyaoycbymezglio\ntrzrgxdjqnmlnzpn\nrumwchfihhihpqui\nffrvnsgrnzemksif\noizlksxineqknwzd\ncirqcprftpjzrxhk\nzrhemeqegmzrpufd\nkqgatudhxgzlgkey\nsyjugymeajlzffhq\nnlildhmgnwlopohp\nflcszztfbesqhnyz\nohzicmqsajyqptrw\nebyszucgozsjbelq\nenxbgvvcuqeloxud\nubwnvecbsmhkxwuk\nnoifliyxvlkqphbo\nhazlqpetgugxxsiz\nihdzoerqwqhgajzb\nivrdwdquxzhdrzar\nsynwycdvrupablib\nmqkdjkntblnmtvxj\nqmmvoylxymyovrnq\npjtuxskkowutltlq\ngchrqtloggkrjciz\nnamzqovvsdipazae\nyfokqhkmakyjzmys\niapxlbuoiwqfnozm\nfbcmlcekgfdurqxe\nednzgtczbplwxjlq\ngdvsltzpywffelsp\noaitrrmpqdvduqej\ngseupzwowmuuibjo\ndfzsffsqpaqoixhh\ntclhzqpcvbshxmgx\ncfqkptjrulxiabgo\niraiysmwcpmtklhf\nznwjlzodhktjqwlm\nlcietjndlbgxzjht\ngdkcluwjhtaaprfo\nvbksxrfznjzwvmmt\nvpfftxjfkeltcojl\nthrmzmeplpdespnh\nyafopikiqswafsit\nxxbqgeblfruklnhs\nqiufjijzbcpfdgig\nikksmllfyvhyydmi\nsknufchjdvccccta\nwpdcrramajdoisxr\ngrnqkjfxofpwjmji\nlkffhxonjskyccoh\nnpnzshnoaqayhpmb\nfqpvaamqbrnatjia\noljkoldhfggkfnfc\nihpralzpqfrijynm\ngvaxadkuyzgbjpod\nonchdguuhrhhspen\nuefjmufwlioenaus\nthifdypigyihgnzo\nugqblsonqaxycvkg\nyevmbiyrqdqrmlbw\nbvpvwrhoyneorcmm\ngbyjqzcsheaxnyib\nknhsmdjssycvuoqf\nnizjxiwdakpfttyh\nnwrkbhorhfqqoliz\nynsqwvwuwzqpzzwp\nyitscrgexjfclwwh\ndhajwxqdbtrfltzz\nbmrfylxhthiaozpv\nfrvatcvgknjhcndw\nxlvtdmpvkpcnmhya\npxpemuzuqzjlmtoc\ndijdacfteteypkoq\nknrcdkrvywagglnf\nfviuajtspnvnptia\nxvlqzukmwbcjgwho\nbazlsjdsjoeuvgoz\nnslzmlhosrjarndj\nmenvuwiuymknunwm\nuavfnvyrjeiwqmuu\nyrfowuvasupngckz\ntaevqhlrcohlnwye\nskcudnogbncusorn\nomtnmkqnqedsajfv\nyqmgsqdgsuysqcts\nodsnbtyimikkbmdd\nvuryaohxdvjllieb\ndhaxldeywwsfamlo\nopobvtchezqnxpak\npzfnegouvsrfgvro\nrzkcgpxdslzrdktu\nksztdtqzxvhuryam\nctnqnhkcooqipgkh\npyqbbvrzdittqbgm\nkoennvmolejeftij\nrvzlreqikqlgyczj\nxrnujfoyhonzkdgd\nmmsmhkxaiqupfjil\nypjwoemqizddvyfd\nqgugcxnbhvgahykj\ncviodlsrtimbkgmy\nxbfbbechhmrjxhnw\npsuipaoucfczfxkp\nhdhwcpeuptgqqvim\ngsxlruhjeaareilr\nvgyqonnljuznyrhk\neewezahlumervpyu\niiolebrxfadtnigy\ntdadlrodykrdfscn\nocvdtzjxrhtjurpo\ngidljbuvuovkhhrf\nqwfcpilbjwzboohd\nxzohxonlezuiupbg\nvslpbkkqgvgbcbix\npivzqrzfxosbstzn\nfyqcfboevcqmbhhs\nyqsrneacnlxswojx\nheicqpxxyrwcbsjz\nyzynmnnoumkmlbeh\nbncadbjdvvmczylw\nhlnjskgfzbgmigfn\nfphpszymugpcykka\nzbifcktanxpmufvy\nsaklpkhoyfeqbguy\nnqtqfcfxmpivnjyo\nlocygrwerxlsvzqm\nqqflecydqvlogjme\nnjklmixvgkzpgppf\nugzkpjwjflaswyma\nlriousvkbeftslcy\nnsvsauxzfbbotgmh\ntblcpuhjyybrlica\nhqwshxcilwtmxrsf\nxojwroydfeoqupup\ntikuzsrogpnohpib\nlayenyqgxdfggloc\nnqsvjvbrpuxkqvmq\nivchgxkdlfjdzxmk\nuoghiuosiiwiwdws\ntwsgsfzyszsfinlc\nwaixcmadmhtqvcmd\nzkgitozgrqehtjkw\nxbkmyxkzqyktmpfi\nqlyapfmlybmatwxn\nntawlvcpuaebuypf\nclhebxqdkcyndyof\nnrcxuceywiklpemc\nlmurgiminxpapzmq\nobalwqlkykzflxou\nhuvcudpiryefbcye\nzlxbddpnyuyapach\ngqfwzfislmwzyegy\njhynkjtxedmemlob\nhmrnvjodnsfiukex\npstmikjykzyavfef\nwuwpnscrwzsyalyt\nhksvadripgdgwynm\ntvpfthzjleqfxwkh\nxpmrxxepkrosnrco\nqjkqecsnevlhqsly\njjnrfsxzzwkhnwdm\npehmzrzsjngccale\nbsnansnfxduritrr\nejzxkefwmzmbxhlb\npceatehnizeujfrs\njtidrtgxopyeslzl\nsytaoidnamfwtqcr\niabjnikomkgmyirr\neitavndozoezojsi\nwtsbhaftgrbqfsmm\nvvusvrivsmhtfild\nqifbtzszfyzsjzyx\nifhhjpaqatpbxzau\netjqdimpyjxiuhty\nfvllmbdbsjozxrip\ntjtgkadqkdtdlkpi\nxnydmjleowezrecn\nvhcbhxqalroaryfn\nscgvfqsangfbhtay\nlbufpduxwvdkwhmb\ntshipehzspkhmdoi\ngtszsebsulyajcfl\ndlrzswhxajcivlgg\nkgjruggcikrfrkrw\nxxupctxtmryersbn\nhljjqfjrubzozxts\ngiaxjhcwazrenjzs\ntyffxtpufpxylpye\njfugdxxyfwkzqmgv\nkbgufbosjghahacw\nxpbhhssgegmthwxb\nnpefofiharjypyzk\nvelxsseyxuhrpycy\nsglslryxsiwwqzfw\nsusohnlpelojhklv\nlfnpqfvptqhogdmk\nvtcrzetlekguqyle\njlyggqdtamcjiuxn\nolxxqfgizjmvigvl\ncyypypveppxxxfuq\nhewmxtlzfqoqznwd\njzgxxybfeqfyzsmp\nxzvvndrhuejnzesx\nesiripjpvtqqwjkv\nxnhrwhjtactofwrd\nknuzpuogbzplofqx\ntihycsdwqggxntqk\nxkfywvvugkdalehs\ncztwdivxagtqjjel\ndsaslcagopsbfioy\ngmowqtkgrlqjimbl\nctcomvdbiatdvbsd\ngujyrnpsssxmqjhz\nnygeovliqjfauhjf\nmmgmcvnuppkbnonz\nbhipnkoxhzcotwel\nwkwpgedgxvpltqid\nmliajvpdocyzcbot\nkqjhsipuibyjuref\nzqdczykothbgxwsy\nkoirtljkuqzxioaz\naudpjvhmqzvhzqas\ncxyhxlhntyidldfx\niasgocejboxjgtkx\nabehujmqotwcufxp\nfmlrzqmazajxeedl\nknswpkekbacuxfby\nyvyalnvrxgstqhxm\nsjnrljfrfuyqfwuw\nssaqruwarlvxrqzm\niaxbpeqqzlcwfqjz\nuwyxshjutkanvvsc\nuxwrlwbblcianvnb\nnodtifgrxdojhneh\nmloxjfusriktxrms\nlkfzrwulbctupggc\ngcrjljatfhitcgfj\ntkdfxeanwskaivqs\nypyjxqtmitwubbgt\nssxbygzbjsltedjj\nzdrsnoorwqfalnha\nxlgmissaiqmowppd\nazhbwhiopwpguiuo\nfydlahgxtekbweet\nqtaveuqpifprdoiy\nkpubqyepxqleucem\nwlqrgqmnupwiuory\nrwyocktuqkuhdwxz\nabzjfsdevoygctqv\nzsofhaqqghncmzuw\nlqbjwjqxqbfgdckc\nbkhyxjkrqbbunido\nyepxfjnnhldidsjb\nbuilayfduxbppafc\nwedllowzeuswkuez\ngverfowxwtnvgrmo\ntpxycfumxdqgntwf\nlqzokaoglwnfcolw\nyqsksyheyspmcdqt\nvufvchcjjcltwddl\nsaeatqmuvnoacddt\ndxjngeydvsjbobjs\nucrcxoakevhsgcep\ncajgwjsfxkasbayt\nhknzmteafsfemwuv\nxxwhxwiinchqqudr\nusfenmavvuevevgr\nkxcobcwhsgyizjok\nvhqnydeboeunnvyk\nbgxbwbxypnxvaacw\nbwjzdypacwgervgk\nrrioqjluawwwnjcr\nfiaeyggmgijnasot\nxizotjsoqmkvhbzm\nuzphtrpxwfnaiidz\nkihppzgvgyoncptg\nhfbkfrxwejdeuwbz\nzgqthtuaqyrxicdy\nzitqdjnnwhznftze\njnzlplsrwovxlqsn\nbmwrobuhwnwivpca\nuuwsvcdnoyovxuhn\nnmfvoqgoppoyosaj\nhxjkcppaisezygpe\nicvnysgixapvtoos\nvbvzajjgrmjygkhu\njinptbqkyqredaos\ndpmknzhkhleawfvz\nouwwkfhcedsgqqxe\nowroouiyptrijzgv\nbewnckpmnbrmhfyu\nevdqxevdacsbfbjb\ncatppmrovqavxstn\ndqsbjibugjkhgazg\nmkcldhjochtnvvne\nsblkmhtifwtfnmsx\nlynnaujghehmpfpt\nvrseaozoheawffoq\nytysdzbpbazorqes\nsezawbudymfvziff\nvrlfhledogbgxbau\nbipdlplesdezbldn\nermaenjunjtbekeo\neyaedubkthdecxjq\ngbzurepoojlwucuy\nrsiaqiiipjlouecx\nbeqjhvroixhiemtw\nbuzlowghhqbcbdwv\nldexambveeosaimo\nfpyjzachgrhxcvnx\nkomgvqejojpnykol\nfxebehjoxdujwmfu\njnfgvheocgtvmvkx\nqmcclxxgnclkuspx\nrsbelzrfdblatmzu\nvexzwqjqrsenlrhm\ntnfbkclwetommqmh\nlzoskleonvmprdri\nnnahplxqscvtgfwi\nubqdsflhnmiayzrp\nxtiyqxhfyqonqzrn\nomdtmjeqhmlfojfr\ncnimgkdbxkkcnmkb\ntapyijgmxzbmqnks\nbyacsxavjboovukk\nawugnhcrygaoppjq\nyxcnwrvhojpuxehg\nbtjdudofhxmgqbao\nnzqlfygiysfuilou\nnubwfjdxavunrliq\nvqxmmhsbmhlewceh\nygavmcybepzfevrp\nkgflmrqsvxprkqgq\niaqyqmcaedscmakk\ncvbojnbfmrawxzkh\njjjrprbnlijzatuw\nlcsudrrfnnggbrmk\nqzgxbiavunawfibc\ngnnalgfvefdfdwwg\nnokmiitzrigxavsc\netzoxwzxqkkhvais\nurxxfacgjccieufi\nlqrioqhuvgcotuec\ndydbaeyoypsbftra\nhhrotenctylggzaf\nevctqvzjnozpdxzu\ntbpvithmorujxlcp\npllbtcbrtkfpvxcw\nfzyxdqilyvqreowv\nxdleeddxwvqjfmmt\nfcldzthqqpbswoin\nsgomzrpjfmvgwlzi\naxjyskmtdjbxpwoz\nhcvaevqxsmabvswh\nlfdlsfcwkwicizfk\nisjbwpzdognhoxvm\noqnexibqxlyxpluh\nzqfbgodsfzwgcwuf\nkvmnwruwsjllbldz\nkghazimdyiyhmokj\nuiktgpsxpoahofxn\nzkdwawxargcmidct\nftbixlyiprshrjup\nnofhmbxififwroeg\nmcdaqrhplffxrcdt\nfbjxnwojcvlawmlb\nrizoftvwfdhiwyac\neduogrtyhxfwyars\nzoikunqxgjwfqqwr\nzxwbbpmvctzezaqh\nnghujwyeabwdqnop\nvcxamijpoyyksogn\njnckdbuteoqlsdae\njurfqqawafmsiqwv\ninepmztrzehfafie\ntznzkyvzodbrtscf\nxewbavjeppflwscl\nucndzsorexjlnplo\njpxbctscngxgusvu\nmfmygcllauzuoaok\noibkuxhjmhxhhzby\nzjkslwagmeoisunw\navnnxmopdgvmukuu\njmaargejcwboqhkt\nyacmpeosarsrfkrv\niqhgupookcaovwgh\nebjkdnxwtikqzufc\nimdhbarytcscbsvb\nifyibukeffkbqvcr\naloighmyvwybtxhx\nyszqwrutbkiwkxjg\nxyholyzlltjhsuhp\ngykhmrwucneoxcrf\nbadkdgqrpjzbabet\nsunaucaucykwtkjj\npumqkglgfdhneero\nusgtyuestahlydxq\nxmfhflphzeudjsjm\nknywgmclisgpootg\nmtojnyrnvxtweuzb\nuuxufbwfegysabww\nvobhwwocqttlbsik\nyuydfezeqgqxqmnd\nwbqgqkwbibiilhzc\nsfdmgxsbuzsawush\nilhbxcfgordyxwvp\nahqoavuysblnqaeg\nplwgtvpgotskmsey\newjcmzkcnautrrmp\ntyekgzbznlikcyqj\nbqzctiuaxpriuiga\nbimvbfjkiupyqiys\nmpqtbcxfhwymxncw\nhtemlptvqhharjgb\nmqbsmsruwzzxgcxc\nzjyedjwhnvteuaid\npzoelkoidwglpttc\nefydnsvlfimvwxhx\ngfyhgoeiyjcgfyze\ndeqtomhwopmzvjlt\ncasafubtkoopuaju\nyylsfarntbucfulg\nmgjwsormkjsrrxan\nlkkenpupgmjpnqqd\ntegweszyohsoluot\nlihsfdwxmxvwdxna\nrrefrjjxerphejwb\nguuazonjoebhymtm\nysofqzmfmyneziki\nlmjgaliatcpduoal\nqzthcpjwtgahbebr\nwvakvephyukmpemm\nsimxacxxzfoaeddw\naetgqmiqzxbvbviz\njxlmhdmqggevrxes\nmmuglnjmuddzgaik\nsvopsqhtrslgycgc\nxnvcsiiqrcjkvecn\nkkvumxtvashxcops\nbduflsdyeectvcgl\nvfrxbwmmytjvqnsj\neeqtdneiyiaiofxw\ncrtbgknfacjtwkfl\nuuutuoxdsxolpbhd\nlcrztwzreaswovtn\nhtorkvnvujmjdqzj\nwttzuzvrzlyhfzyf\noraewznfwgdsnhuk\nrctlkqqvkwbgrcgk\ncfehrsrqhzyiwtmz\nkbvxwcumjkhvjpui\nxxlocexbmniiakfo\ngtknkkzvykmlqghl\nkcjuxvkuimhwqrtk\nvohekwkuyuoacuww\nvorctgughscysyfo\nzmjevqplngzswxyq\nqhswdrhrijnatkyo\njoakcwpfggtitizs\njuzlwjijcmtswdtq\nicbyaqohpkemhkip\nrpdxgpzxncedmvzh\nrozkmimbqhbhcddv\nwkkypomlvyglpfpf\njcaqyaqvsefwtaya\nghvmtecoxlebdwnf\nlqrcyiykkkpkxvqt\neqlarfazchmzotev\nvqwndafvmpguggef\ndbfxzrdkkrusmdke\ncmjpjjgndozcmefj\nhbrdcwjuyxapyhlo\nmmforetykbosdwce\nzynfntqwblbnfqik\nsodwujfwlasznaiz\nyyvrivjiqnxzqkfp\nuldbskmmjbqllpnm\nfyhhrmrsukeptynl\nhpfjekktvdkgdkzl\nbozhkoekcxzeorob\nuvpptyfrzkvmtoky\nhkhfprmjdpjvfkcb\nigxzwktwsqhsivqu\nqceomwysgkcylipb\ncglateoynluyeqgc\nxcsdfkpeguxgvpfh\nowjhxlcncdgkqyia\nrpbmrpcesiakqpna\nlueszxiourxsmezb\nzelvsowimzkxliwc\nvzxbttoobtvdtkca\npfxvzphzwscqkzsi\nedsjorainowytbzu\nipsegdaluoiphmnz\nmkhueokfpemywvuw\nurxdnumhylpafdlc\nggluurzavsxkvwkl\nctclphidqgteakox\ntfobosynxsktajuk\njzrmemhxqmzhllif\neemwekimdfvqslsx\nyjkwpzrbanoaajgq\nrlxghzanuyeimfhx\nhozbgdoorhthlqpv\nobkbmflhyanxilnx\nxojrippyxjmpzmsz\nukykmbfheixuviue\nqivlmdexwucqkres\nrmyxxipqkarpjmox\nfgaftctbvcvnrror\nraawxozucfqvasru\ndinpjbdfjfizexdh\ngybxubwnnbuyvjcr\nqrqitdvyoneqyxcg\njqzcfggayzyoqteo\ncikqpvxizpdbmppm\nstfpldgyhfmucjjv\nslzbcuihmimpduri\naufajwfrsorqqsnl\niylmzraibygmgmqj\nlcdyfpcqlktudfmu\npmomzzsdpvgkkliw\nzpplirgtscfhbrkj\nmvhyerxfiljlotjl\nofkvrorwwhusyxjx\nxngzmvcgkqfltjpe\nyxfxaqipmysahqqq\nsdqafdzgfdjuabup\nqcqajmerahcdgxfv\nxqimrqtupbapawro\nqfvkqwidzzrehsbl\nhimixxvueksiqfdf\nvgtfqpuzxxmhrvvd\nadiioqeiejguaost\njnzxuycjxvxehbvm\nxedbpxdhphamoodk\njsrioscmwlsfuxrg\nmtsynnfxunuohbnf\nenamqzfzjunnnkpe\nuwcvfecunobyhces\nciygixtgbsccpftq\newjgcronizkcsfjy\nwztjkoipxsikoimv\njrgalyvfelwxforw\nimylyalawbqwkrwb\nyflwqfnuuvgjsgcj\nwkysyzusldlojoue\nzopllxnidcffcuau\nbscgwxuprxaerskj\nzvnvprxxjkhnkkpq\nnejwxbhjxxdbenid\nchryiccsebdbcnkc\nguoeefaeafhlgvxh\nnzapxrfrrqhsingx\nmkzvquzvqvwsejqs\nkozmlmbchydtxeeo\nkeylygnoqhmfzrfp\nsrwzoxccndoxylxe\nuqjzalppoorosxxo\npotmkinyuqxsfdfw\nqkkwrhpbhypxhiun\nwgfvnogarjmdbxyh\ngkidtvepcvxopzuf\natwhvmmdvmewhzty\npybxizvuiwwngqej\nzfumwnazxwwxtiry\nkeboraqttctosemx\nvtlzxaqdetbhclib\nwjiecykptzexuayl\nejatfnyjjdawepyk\nmpcrobansyssvmju\ngqukndzganeueabm\nukzscvomorucdnqd\nwfydhtbzehgwfazx\nmtwqdzlephqvxqmx\ndltmlfxbjopefibh\natcfrowdflluqtbi\nvowawlophlxaqonw\nvblgdjzvwnocdipw\nuzerzksmkvnlvlhm\nytjwhpaylohorvxd\nsiprvfxvnxcdgofz\ncbhjupewcyjhvtgs\napqtozaofusmfqli\ntmssrtlxfouowqnr\nntutrvwnzzgmokes\nzrsgpwdzokztdpis\nnrobvmsxtfmrqdhv\nkadkaftffaziqdze\nyrovbgcyqtlsnoux\nmodheiwuhntdecqs\ngzhjypwddizemnys\ngaputpwpcsvzxjho\nbgmouxwoajgaozau\noxuapfrjcpyakiwt\nkntwbvhuaahdixzj\nepqjdjbnkxdnaccx\ndspltdvznhypykri\ntdrgqmbnagrxdwtt\nnjfqawzjggmemtbg\nchpemsgwpzjpdnkk\nfpsrobmbqbmigmwk\nflxptsrqaazmprnl\nnzdunrxlcbfklshm\nmiuwljvtkgzdlbnn\nxbhjakklmbhsdmdt\nxwxhsbnrwnegwcov\npwosflhodjaiexwq\nfhgepuluczttfvqh\ntldxcacbvxyamvkt\ngffxatrjglkcehim\ntzotkdrpxkucsdps\nwxheftdepysvmzbe\nqfooyczdzoewrmku\nrvlwikuqdbpjuvoo\nbcbrnbtfrdgijtzt\nvaxqmvuogsxonlgq\nibsolflngegravgo\ntxntccjmqakcoorp\nvrrbmqaxfbarmlmc\ndzspqmttgsuhczto\npikcscjunxlwqtiw\nlwzyogwxqitqfqlv\ngsgjsuaqejtzglym\nfeyeqguxbgmcmgpp\ngmttebyebdwvprkn\nmzuuwbhzdjfdryxu\nfganrbnplymqbzjx\ncvsrbdcvhtxxdmro\nscmgkjlkqukoamyp\nfkgrqbyqpqcworqc\nhjsrvkdibdjarxxb\nsztzziuqroeidcus\npxdfvcpvwaddrzwv\nphdqqxleqdjfgfbg\ncqfikbgxvjmnfncy";

function testData(){
	var word1 = "ugknbfddgicrmopn";
	var word2 = "aaa";
	var word3 = "jchzalrnumimnmhp";
	var word4 = "haegwjzuvuyypxyu";
	var word5 = "dvszwmarrgswjxmb";

	console.log(checkNaughty(word1));
	console.log(checkNaughty(word2));
	console.log(checkNaughty(word3));
	console.log(checkNaughty(word4));
	console.log(checkNaughty(word5));
}

function testDatab(){
	var word1 = "qjhvhtzxzqqjkmpb";
	var word2 = "xxyxx";
	var word3 = "uurcxstgmygtbstg";
	var word4 = "ieodomkazucvgmuy";
	var word5 = "aaa";
	console.log(checkNaughtyV2(word1));
	console.log(checkNaughtyV2(word2));
	console.log(checkNaughtyV2(word3));
	console.log(checkNaughtyV2(word4));
	console.log(checkNaughtyV2(word5));
}

function day5a(words){
	var wordArray=words.split("\n");
	var count=0;
	for(var i=0;i<wordArray.length;i++){
		if(checkNaughty(wordArray[i])){
			count++;
		}
	}
	console.log("Nice Count: "+count);
}

function day5b(words){
	var wordArray=words.split("\n");
	var count=0;
	for(var i=0;i<wordArray.length;i++){
		if(checkNaughtyV2(wordArray[i])){
			count++;
		}
	}
	console.log("Nice Count: "+count);
}

function checkNaughty(inputString){ // returns true if nice, false if naughty.
	var inputArray=inputString.split("");
	var double=false;
	var vowels=0;
	var invalid=false;
	for(var i=0;i<inputArray.length && !invalid;i++){
		if(isVowel(inputArray[i])){
			vowels++;
		}
		if(inputArray[i]===inputArray[(i-1)]){
			double = true;
		}
		if(isInvalid(inputArray[i-1]+ inputArray[i])){
			invalid = true;
		}
	}
	if(!invalid && (vowels>2) && double){
		return true;
	} else {
		return false;
	}
}

function checkNaughtyV2(inputString){ // returns true if nice, false if naughty.
	var repeat = /(..).*\1+/;
	var skipReg=/(.).\1{1,}/;

	var repeatResult=repeat.test(inputString);
	var skipResult=skipReg.test(inputString);
	return repeatResult && skipResult;
}

function isInvalid(inString){
	if(inString==="ab" || inString==="cd" || inString==="pq" || inString==="xy"){
		return true;
	}
	return false;
}

function isVowel(character){
	if(character==="a"){
		return true;
	}
	if(character==="e"){
		return true;
	}
	if(character==="i"){
		return true;
	}
	if(character==="o"){
		return true;
	}
	if(character==="u"){
		return true;
	}
	return false;
}

//testData();
//day5a(wordList);
//testDatab();
day5b(wordList);